version: "3.9"
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    env_file:
      - jupyter.env
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
